<?xml version="1.0" encoding="UTF-8"?><testrun name="CalculatorTests" project="Java1-Chapter14" tests="6" started="6" failures="0" errors="1" ignored="0">
  <testsuite name="com.skilldistillery.calc.CalculatorTests" time="0.0">
    <testcase name="test_divide_double_divdes_first_number_by_second_number_with_decimals" classname="com.skilldistillery.calc.CalculatorTests" time="0.0"/>
    <testcase name="test_multiply_multiplies_two_numbers" classname="com.skilldistillery.calc.CalculatorTests" time="0.0"/>
    <testcase name="test_subtract_subtracts_two_numbers" classname="com.skilldistillery.calc.CalculatorTests" time="0.0"/>
    <testcase name="test_add_adds_two_numbers" classname="com.skilldistillery.calc.CalculatorTests" time="0.0"/>
    <testcase name="test_divideInts_divides_first_number_by_second_number_and_returns_whole_number_truncated" classname="com.skilldistillery.calc.CalculatorTests" time="0.0"/>
    <testcase name="test_divideInts_throws_ArithmeticException_when_arg2_equals_zero" classname="com.skilldistillery.calc.CalculatorTests" time="0.0">
      <error>java.lang.Exception: Unexpected exception, expected&lt;com.skilldistillery.calc.CannotDoThatException&gt; but was&lt;java.lang.ArithmeticException&gt;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ArithmeticException: / by zero
	at com.skilldistillery.calc.Calculator.divideInts(Calculator.java:17)
	at com.skilldistillery.calc.CalculatorTests.test_divideInts_throws_ArithmeticException_when_arg2_equals_zero(CalculatorTests.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 17 more

</error>
    </testcase>
  </testsuite>
</testrun>
